export const CHANGE_TITLE_FIELD = "CHANGE_TITLE_FIELD";
export const CHANGE_BODY_FIELD = "CHANGE_BODY_FIELD";
export const REQUEST_PROJECTS_PENDING = "REQUEST_PROJECTS_PENDING";
export const REQUEST_PROJECTS_SUCCESS = "REQUEST_PROJECTS_SUCCESS";
export const REQUEST_PROJECTS_FAILED = "REQUEST_PROJECTS_FAILED";
export const SELECT_LAST_PROJECTS_ON_LOAD = "SELECT_LAST_PROJECTS_ON_LOAD";

export const OPEN_INSERT_PROJECT_WINDOW = "OPEN_INSERT_PROJECT_WINDOW";
export const CLOSE_INSERT_PROJECT_WINDOW = "CLOSE_INSERT_PROJECT_WINDOW";
export const OPEN_EDIT_PROJECT_WINDOW = "OPEN_EDIT_PROJECT_WINDOW";
export const CLOSE_EDIT_PROJECT_WINDOW = "CLOSE_EDIT_PROJECT_WINDOW";
export const SELECT_EDIT_PROJECT = "SELECT_EDIT_PROJECT";

export const CHANGE_EDIT_TITLE_FIELD = "CHANGE_EDIT_TITLE_FIELD";
export const CHANGE_EDIT_BODY_FIELD = "CHANGE_EDIT_BODY_FIELD";

export const SWITCH_INSERTION_PROJECT_SUCCESS =
  "SWITCH_INSERTION_PROJECT_SUCCESS";
export const SWITCH_UPDATE_PROJECT_SUCCESS = "SWITCH_UPDATE_PROJECT_SUCCESS";
export const SWITCH_DELETE_PROJECT_SUCCESS = "SWITCH_DELETE_PROJECT_SUCCESS";

export const SWITCH_INSERTION_PROJECT_SUCCESS_CLOSE =
  "SWITCH_INSERTION_PROJECT_SUCCESS_CLOSE";
export const SWITCH_UPDATE_PROJECT_SUCCESS_CLOSE =
  "SWITCH_UPDATE_PROJECT_SUCCESS_CLOSE";
export const SWITCH_DELETE_PROJECT_SUCCESS_CLOSE =
  "SWITCH_DELETE_PROJECT_SUCCESS_CLOSE";

export const RESET_INSERT_PROJECT_FIELDS = "RESET_INSERT_PROJECT_FIELDS";
export const RESET_UPDATE_PROJECT_FIELDS = "RESET_UPDATE_PROJECT_FIELDS";
export const RENDER_NEW_PROJECT = "RENDER_NEW_PROJECT";
export const RENDER_UPDATE_PROJECT = "RENDER_UPDATE_PROJECT";
export const RENDER_DELETE_PROJECT = "RENDER_DELETE_PROJECT";
export const SET_PREVIEW_IMAGE_2 = "SET_PREVIEW_IMAGE_2";
export const SET_PREVIEW_IMAGE_1 = "SET_PREVIEW_IMAGE_1";
export const SET_UPLOAD_FILE_1 = "SET_UPLOAD_FILE_1";
export const SET_UPLOAD_FILE_2 = "SET_UPLOAD_FILE_2";
