export const SWITCH_INSERTION_SUCCESS = "SWITCH_INSERTION_SUCCESS";
export const SWITCH_UPDATE_SUCCESS = "SWITCH_UPDATE_SUCCESS";
export const SWITCH_DELETE_SUCCESS = "SWITCH_DELETE_SUCCESS";
export const SWITCH_INSERTION_SUCCESS_CLOSE = "SWITCH_INSERTION_SUCCESS_CLOSE";
export const SWITCH_UPDATE_SUCCESS_CLOSE = "SWITCH_UPDATE_SUCCESS_CLOSE";
export const SWITCH_DELETE_SUCCESS_CLOSE = "SWITCH_DELETE_SUCCESS_CLOSE";