export const CHANGE_TITLE_FIELD = "CHANGE_TITLE_FIELD";
export const CHANGE_POST_BODY_FIELD = "CHANGE_POST_BODY_FIELD";
export const REQUEST_POSTS_PENDING = "REQUEST_POSTS_PENDING";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";
export const REQUEST_POSTS_FAILED = "REQUEST_POSTS_FAILED";
export const SELECT_LAST_POSTS_ON_LOAD = "SELECT_LAST_POSTS_ON_LOAD";

export const OPEN_INSERT_POST_WINDOW = "OPEN_INSERT_POST_WINDOW";
export const CLOSE_INSERT_POST_WINDOW = "CLOSE_INSERT_POST_WINDOW";
export const OPEN_EDIT_POST_WINDOW = "OPEN_EDIT_POST_WINDOW";
export const CLOSE_EDIT_POST_WINDOW = "CLOSE_EDIT_POST_WINDOW";
export const SELECT_EDIT_POST = "SELECT_EDIT_POST";

export const CHANGE_EDIT_TITLE_FIELD = "CHANGE_EDIT_TITLE_FIELD";
export const CHANGE_EDIT_POST_BODY_FIELD = "CHANGE_EDIT_POST_BODY_FIELD";

export const RESET_INSERT_POST_FIELDS = "RESET_INSERT_POST_FIELDS";
export const RESET_UPDATE_POST_FIELDS = "RESET_UPDATE_POST_FIELDS";
export const RENDER_NEW_POST = "RENDER_NEW_POST";
export const RENDER_UPDATE_POST = "RENDER_UPDATE_POST";
export const RENDER_DELETE_POST = "RENDER_DELETE_POST";
export const SET_PREVIEW_POST_IMAGE_1 = "SET_PREVIEW_POST_IMAGE_1";
export const SET_UPLOAD_FILE_1 = "SET_UPLOAD_FILE_1";
export const SET_DELETE_IMAGE = "SET_DELETE_IMAGE";
export const SET_DELETE_TO_FALSE = "SET_DELETE_TO_FALSE";
