export const CHANGE_TITLE_FIELD = "CHANGE_TITLE_FIELD";
export const CHANGE_BODY_FIELD = "CHANGE_BODY_FIELD";
export const REQUEST_POSTS_PENDING = "REQUEST_POSTS_PENDING";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";
export const REQUEST_POSTS_FAILED = "REQUEST_POSTS_FAILED";
export const SELECT_LAST_POSTS_ON_LOAD = "SELECT_LAST_POSTS_ON_LOAD";
