export const RENDER_NEW_PHOTO = "RENDER_NEW_PHOTO";
export const RENDER_UPDATE_PHOTO = "RENDER_UPDATE_PHOTO";
export const RENDER_DELETE_PHOTO = "RENDER_DELETE_PHOTO";
export const REQUEST_SECTION_IMAGES_PENDING = "REQUEST_SECTION_IMAGES_PENDING";
export const REQUEST_SECTION_IMAGES_SUCCESS = "REQUEST_SECTION_IMAGES_SUCCESS";
export const REQUEST_SECTION_IMAGES_FAILED = "REQUEST_SECTION_IMAGES_FAILED";
export const REORDER_SECTION = "REORDER_SECTION";
export const ADD_SECTION_IMAGE = "ADD_SECTION_IMAGE";
