export const CHANGE_TITLE_FIELD = "CHANGE_TITLE_FIELD";
export const CHANGE_BODY_FIELD = "CHANGE_BODY_FIELD";
export const REQUEST_POSTS_PENDING = "REQUEST_POSTS_PENDING";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";
export const REQUEST_POSTS_FAILED = "REQUEST_POSTS_FAILED";
export const SELECT_LAST_POSTS_ON_LOAD = "SELECT_LAST_POSTS_ON_LOAD";

export const OPEN_INSERT_POST_WINDOW = "OPEN_INSERT_POST_WINDOW";
export const CLOSE_INSERT_POST_WINDOW = "CLOSE_INSERT_POST_WINDOW";
export const OPEN_EDIT_POST_WINDOW = "OPEN_EDIT_POST_WINDOW";
export const CLOSE_EDIT_POST_WINDOW = "CLOSE_EDIT_POST_WINDOW";
export const SELECT_EDIT_POST = "SELECT_EDIT_POST";

export const CHANGE_EDIT_TITLE_FIELD = "CHANGE_EDIT_TITLE_FIELD";
export const CHANGE_EDIT_BODY_FIELD = "CHANGE_EDIT_BODY_FIELD";

export const SWITCH_INSERTION_POST_SUCCESS = "SWITCH_INSERTION_POST_SUCCESS";
export const SWITCH_UPDATE_POST_SUCCESS = "SWITCH_UPDATE_POST_SUCCESS";
export const SWITCH_DELETE_POST_SUCCESS = "SWITCH_DELETE_POST_SUCCESS";

export const SWITCH_INSERTION_POST_SUCCESS_CLOSE =
  "SWITCH_INSERTION_POST_SUCCESS_CLOSE";
export const SWITCH_UPDATE_POST_SUCCESS_CLOSE =
  "SWITCH_UPDATE_POST_SUCCESS_CLOSE";
export const SWITCH_DELETE_POST_SUCCESS_CLOSE =
  "SWITCH_DELETE_POST_SUCCESS_CLOSE";

export const RESET_INSERT_POST_FIELDS = "RESET_INSERT_POST_FIELDS";
export const RESET_UPDATE_POST_FIELDS = "RESET_UPDATE_POST_FIELDS";
export const RENDER_NEW_POST = "RENDER_NEW_POST";
export const RENDER_UPDATE_POST = "RENDER_UPDATE_POST";
export const RENDER_DELETE_POST = "RENDER_DELETE_POST";;
