export const CHANGE_MESSAGE_FIELD = "CHANGE_MESSAGE_FIELD";
export const CHANGE_SUBJECT_FIELD = "CHANGE_SUBJECT_FIELD";
export const CHANGE_SENDING_FILES = "CHANGE_SENDING_FILES";
export const REMOVE_SENDING_FILES = "REMOVE_SENDING_FILES";
export const RESET_EMAIL_FIELDS = "RESET_EMAIL_FIELDS";
export const SENDING_EMAIL_PENDING = "SENDING_EMAIL_PENDING";
export const SENDING_EMAIL_SUCCESS = "SENDING_EMAIL_SUCCESS";
export const SENDING_EMAIL_ERROR = "SENDING_EMAIL_ERROR";