export const CHANGE_INSERT_TENANT_NAME = "CHANGE_INSERT_TENANT_NAME";
export const CHANGE_INSERT_TENANT_EMAIL = "CHANGE_INSERT_TENANT_EMAIL";
export const CHANGE_INSERT_TENANT_HOUSENUMBER =
  "CHANGE_INSERT_TENANT_HOUSENUMBER";
export const CHANGE_EDIT_TENANT_NAME = "CHANGE_EDIT_TENANT_NAME";
export const CHANGE_EDIT_TENANT_EMAIL = "CHANGE_EDIT_TENANT_EMAIL";
export const CHANGE_EDIT_TENANT_HOUSENUMBER = "CHANGE_EDIT_TENANT_HOUSENUMBER";
export const OPEN_INSERT_TENANT_WINDOW = "OPEN_INSERT_TENANT_WINDOW";
export const CLOSE_INSERT_TENANT_WINDOW = "CLOSE_INSERT_TENANT_WINDOW";
export const OPEN_EDIT_TENANT_WINDOW = "OPEN_EDIT_TENANT_WINDOW";
export const CLOSE_EDIT_TENANT_WINDOW = "CLOSE_EDIT_TENANT_WINDOW";
export const SWITCH_INSERTION_TENANT_SUCCESS =
  "SWITCH_INSERTION_TENANT_SUCCESS";
export const SWITCH_INSERTION_TENANT_SUCCESS_CLOSE =
  "SWITCH_INSERTION_TENANT_SUCCESS_CLOSE";
export const RENDER_NEW_TENANT = "RENDER_NEW_TENANT";
export const RESET_UPDATE_TENANT_FIELDS = "RESET_UPDATE_TENANT_FIELDS";
export const SWITCH_UPDATE_TENANT_SUCCESS = "SWITCH_UPDATE_TENANT_SUCCESS";
export const SWITCH_UPDATE_TENANT_SUCCESS_CLOSE =
  "SWITCH_UPDATE_TENANT_SUCCESS_CLOSE";
export const SWITCH_DELETE_TENANT_SUCCESS = "SWITCH_DELETE_TENANT_SUCCESS";
export const SWITCH_DELETE_TENANT_SUCCESS_CLOSE =
  "SWITCH_DELETE_TENANT_SUCCESS_CLOSE";
export const RESET_INSERT_TENANT_FIELDS = "RESET_INSERT_TENANT_FIELDS";
export const SELECT_EDIT_TENANT = "SELECT_EDIT_TENANT";
export const REQUEST_TENANTS_PENDING = "REQUEST_TENANTS_PENDING";
export const REQUEST_TENANTS_SUCCESS = "REQUEST_TENANTS_SUCCESS";
export const REQUEST_TENANTS_FAILED = "REQUEST_TENANTS_FAILED";
export const ACTION_TENANT_PENDING = "ACTION_TENANT_PENDING";
export const ACTION_TENANT_SUCCESS = "ACTION_TENANT_SUCCESS";
export const ACTION_TENANTS_FAILED = "ACTION_TENANTS_FAILED";
