// export const BACKEND_URI = "https://lesnayagavan.ru";
export const BACKEND_URI = "http://localhost:8080";

export const INSERT_TENANT = "INSERT_TENANT";
export const DELETE_TENANT = "DELETE_TENANT";
export const UPDATE_TENANT = "UPDATE_TENANT";
export const REQUEST_TENANTS_PENDING = "REQUEST_TENANTS_PENDING";
export const REQUEST_TENANTS_SUCCESS = "REQUEST_TENANTS_SUCCESS";
export const REQUEST_TENANTS_FAILED = "REQUEST_TENANTS_FAILED";
export const SELECT_ALL_TENANTS = "SELECT_ALL_TENANTS";
export const RESET_ALL_TENANTS = "RESET_ALL_TENANTS";

export const SELECT_ALL_TENANTS_ON_LOAD = "SELECT_ALL_TENANTS_ON_LOAD";
export const CHANGE_SELECTED_TENANTS = "CHANGE_SELECTED_TENANTS";

export const ACTION_TENANT_PENDING = "ACTION_TENANT_PENDING";
export const ACTION_TENANT_SUCCESS = "ACTION_TENANT_SUCCESS";
export const ACTION_TENANTS_FAILED = "ACTION_TENANTS_FAILED";

export const ON_CORRECT_RESPONSE = "ON_CORRECT_RESPONSE";
export const ON_WRONG_RESPONSE = "ON_WRONG_RESPONSE";

export const AUTH_PENDING = "AUTH_PENDING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_SUCCESS";
export const SWITCH_ACCOUNT_UPDATE_SUCCESS = "SWITCH_ACCOUNT_UPDATE_SUCCESS";
export const SWITCH_ACCOUNT_UPDATE_SUCCESS_CLOSE =
  "SWITCH_ACCOUNT_UPDATE_SUCCESS_CLOSE";
export const SWITCH_SNACK_STATUS = "SWITCH_SNACK_STATUS";
export const SNACK_STATUS_CLOSE = "SNACK_STATUS_CLOSE";
export const SNACK_STATUS_OPEN = "SNACK_STATUS_OPEN";
export const SNACK_MESSAGE_CHANGE = "SNACK_MESSAGE_CHANGE";
export const SNACK_TYPE_CHANGE = "SNACK_TYPE_CHANGE";

export const ALERT_STATUS_CLOSE = "ALERT_STATUS_CLOSE";
export const ALERT_STATUS_OPEN = "ALERT_STATUS_OPEN";
export const ALERT_STATUS_ACCEPT = "ALERT_STATUS_ACCEPT";
