export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_FAILED";

export const INSERT_TENANT = "INSERT_TENANT";
export const DELETE_TENANT = "DELETE_TENANT";
export const UPDATE_TENANT = "UPDATE_TENANT";
export const REQUEST_TENANTS_PENDING = "REQUEST_TENANTS_PENDING";
export const REQUEST_TENANTS_SUCCESS = "REQUEST_TENANTS_SUCCESS";
export const REQUEST_TENANTS_FAILED = "REQUEST_TENANTS_FAILED";
export const SEND_MESSAGES = "SEND_MESSAGES";
export const UPLOAD_FILES = "UPLOAD_FILES";

export const CHANGE_INSERT_NAME_FIELD = "CHANGE_INSERT_NAME_FIELD";
export const CHANGE_INSERT_EMAIL_FIELD = "CHANGE_INSERT_EMAIL_FIELD";
export const CHANGE_INSERT_HOUSENUMBER_FIELD =
  "CHANGE_INSERT_HOUSENUMBER_FIELD";
export const CHANGE_UPDATE_NAME_FIELD = "CHANGE_UPDATE_NAME_FIELD";
export const CHANGE_UPDATE_EMAIL_FIELD = "CHANGE_UPDATE_NAME_FIELD";
export const CHANGE_DELETE_HOUSENUMBER_FIELD =
  "CHANGE_UPDATE_HOUSENUMBER_FIELD";
export const CHANGE_MESSAGE_FIELD = "CHANGE_MESSAGE_FIELD";
export const CHANGE_SUBJECT_FIELD = "CHANGE_SUBJECT_FIELD";
