export const CHANGE_UPDATE_ADMIN_EMAIL_FIELD =
  "CHANGE_UPDATE_ADMIN_EMAIL_FIELD";
export const CHANGE_UPDATE_ADMIN_MAIL_PASS_FIELD =
  "CHANGE_UPDATE_ADMIN_MAIL_PASS_FIELD";
export const CHANGE_UPDATE_ADMIN_ACCOUNT_PASS_OLD_FIELD =
  "CHANGE_UPDATE_ADMIN_ACCOUNT_PASS_OLD_FIELD";
export const CHANGE_UPDATE_ADMIN_ACCOUNT_PASS_NEW_FIELD =
  "CHANGE_UPDATE_ADMIN_ACCOUNT_PASS_NEW_FIELD";
export const CHANGE_UPDATE_ADMIN_ACCOUNT_PASS_REPEAT_FIELD =
  "CHANGE_UPDATE_ADMIN_ACCOUNT_PASS_REPEAT_FIELD";
export const CHANGE_UPDATE_ADMIN_PHONE_FIELD =
  "CHANGE_UPDATE_ADMIN_PHONE_FIELD";
export const CHANGE_UPDATE_ADMIN_PHONE2_FIELD =
  "CHANGE_UPDATE_ADMIN_PHONE2_FIELD";
export const RESET_EMAIL_SETTINGS_FIELDS = "RESET_EMAIL_SETTINGS_FIELDS";
export const RESET_ACCOUNT_SETTINGS_FIELDS = "RESET_ACCOUNT_SETTINGS_FIELDS";

export const SWITCH_EMAIL_UPDATE_SUCCESS = "SWITCH_EMAIL_UPDATE_SUCCESS";
export const SWITCH_EMAIL_UPDATE_SUCCESS_CLOSE =
  "SWITCH_EMAIL_UPDATE_SUCCESS_CLOSE";
export const SWITCH_ACCOUNT_UPDATE_SUCCESS = "SWITCH_ACCOUNT_UPDATE_SUCCESS";
export const SWITCH_ACCOUNT_UPDATE_SUCCESS_CLOSE =
  "SWITCH_ACCOUNT_UPDATE_SUCCESS_CLOSE";
export const REQUEST_SETTINGS_PENDING = "REQUEST_SETTINGS_PENDING";
export const REQUEST_SETTINGS_SUCCESS = "REQUEST_SETTINGS_SUCCESS";
export const REQUEST_SETTINGS_FAILED = "REQUEST_SETTINGS_FAILED";
