export const CHANGE_PASSWORD_FIELD = "CHANGE_PASSWORD_FIELD";
export const SENDING_PASSWORD_PENDING = "SENDING_PASSWORD_PENDING";
export const SENDING_PASSWORD_SUCCESS = "SENDING_PASSWORD_SUCCESS";
export const SENDING_PASSWORD_ERROR = "SENDING_PASSWORD_ERROR";
export const ON_CORRECT_RESPONSE = "ON_CORRECT_RESPONSE";
export const ON_WRONG_RESPONSE = "ON_WRONG_RESPONSE";