export const CHANGE_UPDATE_TARIFFS_FIELD = "CHANGE_UPDATE_TARIFFS_FIELD";
export const RESET_TARIFFS_FIELDS = "RESET_TARIFFS_FIELDS";
export const REQUEST_TARIFFS_PENDING = "REQUEST_TARIFFS_PENDING";
export const REQUEST_TARIFFS_SUCCESS = "REQUEST_TARIFFS_SUCCESS";
export const REQUEST_TARIFFS_FAILED = "REQUEST_TARIFFS_FAILED";
